import type { DesignDocument, DesignElementBase } from "./schema";
import { parseDesignDocumentV1 } from "./validation";

const NOW = "2026-08-11T08:00:00.000Z";

const BASE: DesignElementBase = {
    id: "placeholder",
    frameId: "frame-main",
    name: "placeholder",
    transform: { x: 0, y: 0, width: 100, height: 100, rotation: 0, flipX: false, flipY: false },
    opacity: 1,
    blendMode: "normal",
    locked: false,
    hidden: false,
};

export function createDesignDocumentFixture(): DesignDocument {
    return parseDesignDocumentV1({
        schemaVersion: 1,
        id: "design-product-campaign",
        revision: 7,
        metadata: { title: "商品图 Campaign", description: "Phase 2 正式契约夹具", createdAt: NOW, updatedAt: NOW },
        workspace: { background: "#e5e7eb", viewport: { x: 10.000_000_1, y: -20, zoom: 0.25 } },
        guides: [
            { id: "guide-workspace-vertical", axis: "vertical", position: 80, frameId: null, locked: false },
            { id: "guide-main-horizontal", axis: "horizontal", position: 1000, frameId: "frame-main", locked: false },
        ],
        frames: [
            { id: "frame-main", name: "Amazon 主图", x: 100, y: 200, width: 2000, height: 2000, background: "#ffffff", locked: false, export: { format: "png", scale: 2, quality: 1, background: "frame" } },
            { id: "frame-social", name: "社媒竖图", x: 2400, y: 200, width: 1080, height: 1350, background: null, locked: false, export: { format: "jpeg", scale: 1, quality: 0.9, background: "white" } },
        ],
        assets: [{ id: "asset-product", kind: "image", name: "商品图", currentVersionId: "asset-product-v2", versionIds: ["asset-product-v1", "asset-product-v2"] }],
        assetVersions: [
            {
                id: "asset-product-v1",
                assetId: "asset-product",
                parentVersionId: null,
                source: "upload",
                locator: { kind: "storage-key", storageKey: "users/user-one/design/product-original.png" },
                mimeType: "image/png",
                width: 3000,
                height: 3000,
                createdAt: NOW,
                provenance: { operation: "upload", sourceElementId: null, generationTaskId: null },
            },
            {
                id: "asset-product-v2",
                assetId: "asset-product",
                parentVersionId: "asset-product-v1",
                source: "derived",
                locator: { kind: "library-asset", libraryAssetId: "library-product-cutout" },
                mimeType: "image/png",
                width: 3000,
                height: 3000,
                createdAt: NOW,
                provenance: { operation: "background-removal", sourceElementId: "element-product", generationTaskId: "task-rembg-one" },
            },
        ],
        elements: [
            {
                ...BASE,
                id: "element-workspace-guide",
                frameId: null,
                name: "Workspace 参考块",
                transform: { ...BASE.transform, x: 12, y: 20 },
                kind: "shape",
                shape: "rectangle",
                fill: "#94a3b8",
                stroke: null,
                strokeWidth: 0,
                cornerRadius: 4,
            },
            {
                ...BASE,
                id: "element-product",
                name: "主商品图",
                transform: { x: 200.000_000_1, y: 250, width: 1200, height: 1200, rotation: 17, flipX: false, flipY: false },
                kind: "image",
                assetVersionId: "asset-product-v2",
                crop: { x: 0.125, y: 0.1, width: 0.75, height: 0.8 },
                fit: "cover",
                cornerRadius: 0,
            },
            {
                ...BASE,
                id: "element-title",
                name: "中英文标题",
                transform: { x: 300, y: 1500, width: 1400, height: 240, rotation: 0, flipX: false, flipY: false },
                kind: "text",
                text: "DQ Bottle / 轻盈一整天",
                fontFamily: "Inter, sans-serif",
                fontSize: 96,
                fontWeight: 700,
                fontStyle: "normal",
                lineHeight: 1.2,
                letterSpacing: 0,
                align: "center",
                verticalAlign: "middle",
                fill: "#111827",
                stroke: null,
                strokeWidth: 0,
            },
            {
                ...BASE,
                id: "element-hidden-badge",
                name: "隐藏徽章",
                hidden: true,
                transform: { ...BASE.transform, x: 30, y: 30 },
                kind: "shape",
                shape: "ellipse",
                fill: "#ef4444",
                stroke: "#ffffff",
                strokeWidth: 2,
                cornerRadius: 0,
            },
            { ...BASE, id: "element-line", name: "分隔线", transform: { x: 100, y: 1400, width: 1800, height: 1, rotation: 0, flipX: false, flipY: false }, kind: "line", stroke: "#334155", strokeWidth: 4, dash: [8, 4], cap: "round" },
            {
                ...BASE,
                id: "element-arrow",
                name: "说明箭头",
                transform: { x: 100, y: 100, width: 400, height: 300, rotation: 0, flipX: false, flipY: false },
                kind: "arrow",
                stroke: "#0f172a",
                strokeWidth: 6,
                dash: [],
                startHead: "none",
                endHead: "arrow",
            },
            {
                ...BASE,
                id: "element-social-product",
                frameId: "frame-social",
                name: "社媒商品图",
                transform: { x: 40, y: 80, width: 900, height: 900, rotation: 0, flipX: false, flipY: false },
                kind: "image",
                assetVersionId: "asset-product-v1",
                crop: null,
                fit: "contain",
                cornerRadius: 12,
            },
        ],
        layers: [
            { scope: "workspace", elementIds: ["element-workspace-guide"] },
            { scope: "frame", frameId: "frame-main", elementIds: ["element-product", "element-line", "element-title", "element-arrow", "element-hidden-badge"] },
            { scope: "frame", frameId: "frame-social", elementIds: ["element-social-product"] },
        ],
        annotations: [
            { id: "annotation-product", text: "保持瓶身商标清晰", target: { kind: "element", elementId: "element-product", region: { x: 0.25, y: 0.1, width: 0.5, height: 0.2 } }, resolved: false, createdAt: NOW, updatedAt: NOW },
            { id: "annotation-social", text: "检查安全区", target: { kind: "frame", frameId: "frame-social", region: { x: 0.05, y: 0.05, width: 0.9, height: 0.9 } }, resolved: false, createdAt: NOW, updatedAt: NOW },
        ],
    });
}
